name: e_com_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: any
  local_auth: any
  google_fonts: any
  svg_flutter: any
  flutter_staggered_grid_view: ^0.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/products.json
    - assets/images/
    - assets/svg/
